package com.songda.recruit.pojo;
// Generated 2018-3-2 20:14:30 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BaseArea generated by hbm2java
 */
@Entity
@Table(name = "base_area", catalog = "recruit")
public class BaseArea implements java.io.Serializable {

	private String id;
	private String prCityId;
	private String name;
	private boolean status;

	public BaseArea() {
	}

	public BaseArea(String id, String prCityId, String name, boolean status) {
		this.id = id;
		this.prCityId = prCityId;
		this.name = name;
		this.status = status;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 6)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "pr_city_id", nullable = false, length = 6)
	public String getPrCityId() {
		return this.prCityId;
	}

	public void setPrCityId(String prCityId) {
		this.prCityId = prCityId;
	}

	@Column(name = "name", nullable = false, length = 60)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
