package com.songda.recruit.pojo;
// Generated 2018-3-2 20:14:30 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BaseCity generated by hbm2java
 */
@Entity
@Table(name = "base_city", catalog = "recruit")
public class BaseCity implements java.io.Serializable {

	private String id;
	private String prProvinceId;
	private String name;
	private boolean status;

	public BaseCity() {
	}

	public BaseCity(String id, String prProvinceId, String name, boolean status) {
		this.id = id;
		this.prProvinceId = prProvinceId;
		this.name = name;
		this.status = status;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 6)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "pr_province_id", nullable = false, length = 6)
	public String getPrProvinceId() {
		return this.prProvinceId;
	}

	public void setPrProvinceId(String prProvinceId) {
		this.prProvinceId = prProvinceId;
	}

	@Column(name = "name", nullable = false, length = 60)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
