package com.songda.recruit.pojo;
// Generated 2018-3-2 20:14:30 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HRebateHis generated by hbm2java
 */
@Entity
@Table(name = "h_rebate_his", catalog = "recruit")
public class HRebateHis implements java.io.Serializable {

	private Long id;
	private Long companyJobId;
	private BigDecimal receiveRebate;
	private BigDecimal payRebate;
	private String channel;
	private Long createBy;
	private Date createTime;
	private Long updateBy;
	private Date updateTime;
	private Boolean delflag;

	public HRebateHis() {
	}

	public HRebateHis(Long companyJobId, BigDecimal receiveRebate, BigDecimal payRebate, String channel, Long createBy,
			Date createTime, Long updateBy, Date updateTime, Boolean delflag) {
		this.companyJobId = companyJobId;
		this.receiveRebate = receiveRebate;
		this.payRebate = payRebate;
		this.channel = channel;
		this.createBy = createBy;
		this.createTime = createTime;
		this.updateBy = updateBy;
		this.updateTime = updateTime;
		this.delflag = delflag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "company_job_id")
	public Long getCompanyJobId() {
		return this.companyJobId;
	}

	public void setCompanyJobId(Long companyJobId) {
		this.companyJobId = companyJobId;
	}

	@Column(name = "receive_rebate", precision = 20)
	public BigDecimal getReceiveRebate() {
		return this.receiveRebate;
	}

	public void setReceiveRebate(BigDecimal receiveRebate) {
		this.receiveRebate = receiveRebate;
	}

	@Column(name = "pay_rebate", precision = 20)
	public BigDecimal getPayRebate() {
		return this.payRebate;
	}

	public void setPayRebate(BigDecimal payRebate) {
		this.payRebate = payRebate;
	}

	@Column(name = "channel", length = 64)
	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	@Column(name = "create_by")
	public Long getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "update_by")
	public Long getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(Long updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "delflag")
	public Boolean getDelflag() {
		return this.delflag;
	}

	public void setDelflag(Boolean delflag) {
		this.delflag = delflag;
	}

}
