package com.songda.recruit.pojo;
// Generated 2018-3-2 20:14:30 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TAgingRebateList generated by hbm2java
 */
@Entity
@Table(name = "t_aging_rebate_list", catalog = "recruit")
public class TAgingRebateList implements java.io.Serializable {

	private Long id;
	private Long companyJobId;
	private Integer ind;
	private BigDecimal price;
	private Integer calculateType;
	private Integer days;
	private Integer months;
	private Long createBy;
	private Date createTime;
	private Long updateBy;
	private Date updateTime;
	private Boolean delflag;

	public TAgingRebateList() {
	}

	public TAgingRebateList(Long companyJobId, Integer ind, BigDecimal price, Integer calculateType, Integer days,
			Integer months, Long createBy, Date createTime, Long updateBy, Date updateTime, Boolean delflag) {
		this.companyJobId = companyJobId;
		this.ind = ind;
		this.price = price;
		this.calculateType = calculateType;
		this.days = days;
		this.months = months;
		this.createBy = createBy;
		this.createTime = createTime;
		this.updateBy = updateBy;
		this.updateTime = updateTime;
		this.delflag = delflag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "company_job_id")
	public Long getCompanyJobId() {
		return this.companyJobId;
	}

	public void setCompanyJobId(Long companyJobId) {
		this.companyJobId = companyJobId;
	}

	@Column(name = "ind")
	public Integer getInd() {
		return this.ind;
	}

	public void setInd(Integer ind) {
		this.ind = ind;
	}

	@Column(name = "price", precision = 20)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "calculate_type")
	public Integer getCalculateType() {
		return this.calculateType;
	}

	public void setCalculateType(Integer calculateType) {
		this.calculateType = calculateType;
	}

	@Column(name = "days")
	public Integer getDays() {
		return this.days;
	}

	public void setDays(Integer days) {
		this.days = days;
	}

	@Column(name = "months")
	public Integer getMonths() {
		return this.months;
	}

	public void setMonths(Integer months) {
		this.months = months;
	}

	@Column(name = "create_by")
	public Long getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "update_by")
	public Long getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(Long updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "delflag")
	public Boolean getDelflag() {
		return this.delflag;
	}

	public void setDelflag(Boolean delflag) {
		this.delflag = delflag;
	}

}
